const express=require('express')
const app=express()
const dotenv=require('dotenv')
const mongoose=require('mongoose')
const categoryRoute=require('./routes/categoryRoute')
const vacancyRoute=require('./routes/vacanciesRoute')
const userRoute=require('./routes/userRoute')
const authRoute=require('./routes/authRoute')
const resumeRoute=require('./routes/resumeRoute')
const authCompanyRoute=require('./routes/authCompanyRoute')
const companyRoute=require('./routes/companyRoute')
dotenv.config()
mongoose.connect(process.env.DB)
.then(()=>console.log('connected to database'))
.catch((err)=>console.log(err))

app.use(express.json())
app.use(express.urlencoded({extended:true}))
app.use("/api/categories",categoryRoute)
app.use("/api/vacancies",vacancyRoute)
app.use('/api/user',userRoute)
app.use('/',authRoute)
app.use('/api/resume',resumeRoute)
app.use('/',authCompanyRoute)
app.use('/api/company',companyRoute)
app.listen(process.env.PORT||6013,console.log(`app runnng on port ${process.env.PORT}`))

